# Frp 客户端配置文件示例
# 将此文件重命名为 frpc.toml 并修改以下配置

# 服务器配置
serverAddr = "your-frp-server.com"  # 替换为你的 frp 服务器地址
serverPort = 7000                   # frp 服务器端口

# 认证配置（如果服务器需要）
# auth.token = "your-token"         # 取消注释并设置你的认证令牌

# 代理配置
[[proxies]]
name = "nchat"                      # 代理名称
type = "tcp"                        # 协议类型
localPort = 8080                    # 本地端口（NChat 接收端口）
# remotePort = 8080                 # 远程端口（可选，让服务器分配）

# 多个代理配置示例
# [[proxies]]
# name = "nchat-udp"
# type = "udp"
# localPort = 8080
# remotePort = 8081 